# Generated by Django 5.2.17 on 2026-08-10 13:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly name, e.g., 'url-shortener'", unique=True)),
                ('description', models.TextField(help_text='Problem statement and context')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('expert', 'Expert')], max_length=10)),
                ('functional_requirements', models.JSONField(default=list, help_text="e.g., ['Users can create short URLs', 'URLs expire after X days']")),
                ('non_functional_requirements', models.JSONField(default=list, help_text="e.g., ['Handle 10K reads/sec', '99.9% availability', 'Low latency (<100ms)']")),
                ('hints', models.JSONField(default=list, help_text='Progressive hints revealed one at a time')),
                ('reference_architecture', models.JSONField(blank=True, help_text='The reference design: {nodes: [...], edges: [...]}', null=True)),
                ('reference_explanation', models.TextField(blank=True, help_text='Markdown explanation of the reference architecture')),
                ('companies', models.JSONField(default=list, help_text="e.g., ['Google', 'Amazon', 'Meta']")),
                ('time_limit_minutes', models.IntegerField(default=45, help_text='Suggested time limit (like a real interview)')),
                ('is_free', models.BooleanField(default=True, help_text='Whether this challenge is available on the free tier')),
                ('order', models.IntegerField(default=0, help_text='Display order within difficulty level')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['difficulty', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(blank=True, help_text='AI-generated score (0-100)', null=True)),
                ('feedback', models.JSONField(blank=True, help_text='Detailed AI feedback on the attempt', null=True)),
                ('time_taken_seconds', models.IntegerField(blank=True, help_text='How long the user took', null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('scored', 'Scored')], default='in_progress', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='challenges.challenge')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
