# Generated by Django 5.2.17 on 2026-08-10 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0001_initial'),
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challengeattempt',
            name='design',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenge_attempt', to='designs.design'),
        ),
    ]
