# Generated by Django 5.2.17 on 2026-08-14 08:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Lucide icon name', max_length=50)),
                ('category', models.CharField(choices=[('challenge', 'Challenge Completion'), ('streak', 'Daily Streak'), ('social', 'Community Interaction')], max_length=50)),
                ('points', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='estimated_difficulty_rating',
            field=models.FloatField(blank=True, help_text='Community rating out of 5.0', null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='solution_patterns',
            field=models.JSONField(default=list, help_text="e.g., ['CQRS', 'Cache-Aside', 'Event-Driven']"),
        ),
    ]
