# Generated by Django 5.2.17 on 2026-08-14 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='badges',
            field=models.JSONField(default=list, help_text='List of earned badge IDs or names'),
        ),
        migrations.AddField(
            model_name='user',
            name='completed_challenges',
            field=models.IntegerField(default=0, help_text='Count of successfully completed challenges'),
        ),
        migrations.AddField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0, help_text='Leaderboard position (calculated periodically)'),
        ),
    ]
