# Generated by Django 5.2.17 on 2026-08-14 08:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('challenges', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(help_text='URL-friendly identifier', unique=True)),
                ('url', models.URLField(help_text='Link to the resource')),
                ('description', models.TextField(help_text='What this resource covers')),
                ('source_type', models.CharField(choices=[('github', 'GitHub Repository'), ('article', 'Article'), ('video', 'Video'), ('documentation', 'Documentation'), ('course', 'Online Course')], max_length=20)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('topics', models.JSONField(default=list, help_text="e.g., ['load-balancing', 'caching', 'databases', 'microservices']")),
                ('author_name', models.CharField(blank=True, max_length=200)),
                ('github_stars', models.IntegerField(blank=True, help_text='GitHub stars count (for repos)', null=True)),
                ('estimated_time_minutes', models.IntegerField(blank=True, help_text='Estimated reading/watching time in minutes', null=True)),
                ('icon', models.CharField(blank=True, help_text='Lucide icon name', max_length=50)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_featured', 'order', '-github_stars'],
            },
        ),
        migrations.CreateModel(
            name='StudyPath',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_challenges', models.ManyToManyField(blank=True, help_text='Challenges to practice after completing this path', related_name='study_paths', to='challenges.challenge')),
            ],
            options={
                'ordering': ['difficulty', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudyPathResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, help_text='Order within the study path')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.resource')),
                ('study_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning.studypath')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('study_path', 'resource')},
            },
        ),
        migrations.AddField(
            model_name='studypath',
            name='resources',
            field=models.ManyToManyField(related_name='study_paths', through='learning.StudyPathResource', to='learning.resource'),
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text="User's personal notes about this resource")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='learning.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'resource')},
            },
        ),
    ]
