# Generated by Django 5.2.17 on 2026-08-10 13:53

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Design title, e.g., 'URL Shortener Architecture'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of the design')),
                ('nodes', models.JSONField(default=list, help_text='React Flow nodes array — all components on the canvas')),
                ('edges', models.JSONField(default=list, help_text='React Flow edges array — connections between components')),
                ('viewport', models.JSONField(default=dict, help_text='Canvas viewport: {x, y, zoom}')),
                ('thumbnail', models.URLField(blank=True, help_text='Auto-generated thumbnail of the design (Cloudinary URL)')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this design is visible in the public gallery')),
                ('tags', models.JSONField(default=list, help_text="Tags like ['microservices', 'high-availability', 'caching']")),
                ('ai_score', models.IntegerField(blank=True, help_text='AI-generated score (0-100)', null=True)),
                ('ai_feedback', models.JSONField(blank=True, help_text='Structured AI feedback: {score, issues: [], suggestions: [], categories: {}}', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Design',
                'verbose_name_plural': 'Designs',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DesignStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version_number', models.IntegerField(help_text='Auto-incrementing version number')),
                ('nodes', models.JSONField(default=list)),
                ('edges', models.JSONField(default=list)),
                ('viewport', models.JSONField(default=dict)),
                ('change_description', models.CharField(blank=True, help_text='Auto-generated or user-provided description of changes', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version_number'],
            },
        ),
    ]
