# Generated by Django 5.2.17 on 2026-08-10 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='author',
            field=models.ForeignKey(help_text='The user who created this design', on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='design',
            name='forked_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forks', to='designs.design'),
        ),
        migrations.AddField(
            model_name='designstar',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stars', to='designs.design'),
        ),
        migrations.AddField(
            model_name='designstar',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starred_designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designs.design'),
        ),
        migrations.AlterUniqueTogether(
            name='designstar',
            unique_together={('user', 'design')},
        ),
        migrations.AlterUniqueTogether(
            name='designversion',
            unique_together={('design', 'version_number')},
        ),
    ]
