/**
 * Universal Icon Component & Registry
 * =====================================
 * Powered by Hugeicons (@hugeicons/react and @hugeicons/core-free-icons).
 * Provides type-safe direct icon imports and dynamic string-based lookups
 * for architecture components, UI controls, indicators, and categories.
 */

import React from 'react';
import { HugeiconsIcon, type IconSvgElement, type HugeiconsProps } from '@hugeicons/react';
import {
  // Brand & Architecture
  CpuIcon,
  ComputerIcon,
  GlobalIcon,
  Globe02Icon,
  Radio01Icon,
  Wifi01Icon,
  GitForkIcon,
  Exchange01Icon,
  ServerIcon,
  ServerStack01Icon,
  CubeIcon,
  Settings01Icon,
  Database01Icon,
  Database02Icon,
  FlashIcon,
  HardDriveIcon,
  Search01Icon,
  Layers01Icon,
  Notification01Icon,
  BellDotIcon,
  Shield01Icon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SecurityLockIcon,
  LockPasswordIcon,
  SquareLock01Icon,
  Wrench01Icon,
  Link01Icon,
  Target01Icon,
  Activity01Icon,
  ChartLineData01Icon,
  ChartIncreaseIcon,
  Coins01Icon,
  Clock01Icon,
  TriangleAlertIcon,
  AlertCircleIcon,
  InformationCircleIcon,
  CheckmarkCircle01Icon,
  Cancel01Icon,
  Tick01Icon,
  TrophyIcon,
  Award01Icon,
  BookOpen01Icon,
  SparklesIcon,
  AiMagicIcon,
  UserIcon,
  UserAdd01Icon,
  LogInIcon,
  LogOutIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  FloppyDiskIcon,
  Delete02Icon,
  Compass01Icon,
  ViewIcon,
  ViewOffIcon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  ArrowDown01Icon,
  ArrowUpRight01Icon,
  StarIcon,
  Idea01Icon,
  BulbIcon,
  Rocket01Icon,
  DollarCircleIcon,
  FilterIcon,
  Menu01Icon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronUpIcon,
  PlusSignIcon,
  MinusSignIcon,
  RotateLeft01Icon,
  RotateRight01Icon,
  Building02Icon,
  SquareIcon,
  DashboardSpeed01Icon,
  CursorPointer01Icon,
  MouseScroll01Icon,
  File01Icon,
  Video01Icon,
  LinkSquare01Icon,
  GraduationCapIcon,
  SourceCodeIcon,
  Brain01Icon,
  Comment01Icon,
  CloudIcon,
  NetworkIcon,
  Grid02Icon,
  LayoutGridIcon,
  GripVerticalIcon,
  FireIcon,
} from '@hugeicons/core-free-icons';

// Export all raw icon symbols for direct import
export {
  CpuIcon,
  ComputerIcon,
  GlobalIcon,
  Globe02Icon,
  Radio01Icon,
  Wifi01Icon,
  GitForkIcon,
  Exchange01Icon,
  ServerIcon,
  ServerStack01Icon,
  CubeIcon,
  Settings01Icon,
  Database01Icon,
  Database02Icon,
  FlashIcon,
  HardDriveIcon,
  Search01Icon,
  Layers01Icon,
  Notification01Icon,
  BellDotIcon,
  Shield01Icon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  SecurityLockIcon,
  LockPasswordIcon,
  SquareLock01Icon,
  Wrench01Icon,
  Link01Icon,
  Target01Icon,
  Activity01Icon,
  ChartLineData01Icon,
  ChartIncreaseIcon,
  Coins01Icon,
  Clock01Icon,
  TriangleAlertIcon,
  AlertCircleIcon,
  InformationCircleIcon,
  CheckmarkCircle01Icon,
  Cancel01Icon,
  Tick01Icon,
  TrophyIcon,
  Award01Icon,
  BookOpen01Icon,
  SparklesIcon,
  AiMagicIcon,
  UserIcon,
  UserAdd01Icon,
  LogInIcon,
  LogOutIcon,
  PlayIcon,
  PauseIcon,
  StopIcon,
  FloppyDiskIcon,
  Delete02Icon,
  Compass01Icon,
  ViewIcon,
  ViewOffIcon,
  ArrowRight01Icon,
  ArrowLeft01Icon,
  ArrowDown01Icon,
  ArrowUpRight01Icon,
  StarIcon,
  Idea01Icon,
  BulbIcon,
  Rocket01Icon,
  DollarCircleIcon,
  FilterIcon,
  Menu01Icon,
  ChevronDownIcon,
  ChevronRightIcon,
  ChevronLeftIcon,
  ChevronUpIcon,
  PlusSignIcon,
  MinusSignIcon,
  RotateLeft01Icon,
  RotateRight01Icon,
  Building02Icon,
  SquareIcon,
  DashboardSpeed01Icon,
  CursorPointer01Icon,
  MouseScroll01Icon,
  File01Icon,
  Video01Icon,
  LinkSquare01Icon,
  GraduationCapIcon,
  SourceCodeIcon,
  Brain01Icon,
  Comment01Icon,
  CloudIcon,
  NetworkIcon,
  Grid02Icon,
  LayoutGridIcon,
  GripVerticalIcon,
  FireIcon,
};

/** Dynamic name to IconSvgElement registry */
export const ICON_NAME_MAP: Record<string, IconSvgElement> = {
  // Canvas & Component Library Identifiers
  Monitor: ComputerIcon,
  Computer: ComputerIcon,
  Globe: GlobalIcon,
  Global: GlobalIcon,
  Radio: Radio01Icon,
  GitFork: GitForkIcon,
  GitBranch: GitForkIcon,
  ArrowRightLeft: Exchange01Icon,
  Exchange: Exchange01Icon,
  Server: ServerIcon,
  Box: CubeIcon,
  Cube: CubeIcon,
  Cog: Settings01Icon,
  Settings: Settings01Icon,
  Database: Database01Icon,
  DatabaseSql: Database01Icon,
  DatabaseNosql: Database02Icon,
  Zap: FlashIcon,
  Flash: FlashIcon,
  HardDrive: HardDriveIcon,
  Search: Search01Icon,
  Layers: Layers01Icon,
  Bell: Notification01Icon,
  Notification: Notification01Icon,
  Shield: Shield01Icon,
  ShieldAlert: ShieldAlertIcon,
  ShieldCheck: ShieldCheckIcon,
  Activity: Activity01Icon,
  Cpu: CpuIcon,
  Network: NetworkIcon,
  Cloud: CloudIcon,

  // UI & Actions
  Play: PlayIcon,
  Pause: PauseIcon,
  Stop: StopIcon,
  Square: SquareIcon,
  Save: FloppyDiskIcon,
  FloppyDisk: FloppyDiskIcon,
  Delete: Delete02Icon,
  Trash: Delete02Icon,
  Trash2: Delete02Icon,
  Sparkles: SparklesIcon,
  AiMagic: AiMagicIcon,
  Trophy: TrophyIcon,
  Award: Award01Icon,
  BookOpen: BookOpen01Icon,
  Book: BookOpen01Icon,
  Compass: Compass01Icon,
  Menu: Menu01Icon,
  LayoutGrid: LayoutGridIcon,
  GripVertical: GripVerticalIcon,
  Plus: PlusSignIcon,
  PlusSign: PlusSignIcon,
  Minus: MinusSignIcon,
  MinusSign: MinusSignIcon,
  RotateLeft: RotateLeft01Icon,
  RotateCcw: RotateLeft01Icon,
  RotateRight: RotateRight01Icon,
  Eye: ViewIcon,
  View: ViewIcon,
  EyeOff: ViewOffIcon,
  ViewOff: ViewOffIcon,
  LogIn: LogInIcon,
  Login: LogInIcon,
  LogOut: LogOutIcon,
  Logout: LogOutIcon,
  User: UserIcon,
  UserPlus: UserAdd01Icon,
  UserAdd: UserAdd01Icon,
  Filter: FilterIcon,
  Clock: Clock01Icon,
  CheckCircle: CheckmarkCircle01Icon,
  CheckCircle2: CheckmarkCircle01Icon,
  CheckmarkCircle: CheckmarkCircle01Icon,
  Check: Tick01Icon,
  Tick: Tick01Icon,
  Circle: CheckmarkCircle01Icon,
  AlertTriangle: TriangleAlertIcon,
  TriangleAlert: TriangleAlertIcon,
  AlertCircle: AlertCircleIcon,
  Info: InformationCircleIcon,
  InformationCircle: InformationCircleIcon,
  X: Cancel01Icon,
  Cancel: Cancel01Icon,
  Cross: Cancel01Icon,
  ChevronDown: ChevronDownIcon,
  ChevronRight: ChevronRightIcon,
  ChevronLeft: ChevronLeftIcon,
  ChevronUp: ChevronUpIcon,
  ArrowRight: ArrowRight01Icon,
  ArrowLeft: ArrowLeft01Icon,
  ArrowDown: ArrowDown01Icon,
  ArrowUpRight: ArrowUpRight01Icon,
  Flame: FireIcon,
  Fire: FireIcon,
  Star: StarIcon,
  Target: Target01Icon,
  Lightbulb: BulbIcon,
  Bulb: BulbIcon,
  Idea: Idea01Icon,
  Rocket: Rocket01Icon,
  Dollar: DollarCircleIcon,
  DollarCircle: DollarCircleIcon,
  Coins: Coins01Icon,
  Wrench: Wrench01Icon,
  Lock: SecurityLockIcon,
  SecurityLock: SecurityLockIcon,
  LockPassword: LockPasswordIcon,
  Building: Building02Icon,
  Building2: Building02Icon,
  Gauge: DashboardSpeed01Icon,
  DashboardSpeed: DashboardSpeed01Icon,
  MousePointerClick: CursorPointer01Icon,
  TrendingUp: ChartIncreaseIcon,
  GraduationCap: GraduationCapIcon,
  Code: SourceCodeIcon,
  Brain: Brain01Icon,
  MessageSquare: Comment01Icon,
  ExternalLink: LinkSquare01Icon,
  FileText: File01Icon,
  Video: Video01Icon,
  Boxes: CubeIcon,
  Link: Link01Icon,
  Link2: Link01Icon,
  PenTool: Wrench01Icon,
  Type: File01Icon,
  PartyPopper: TrophyIcon,
};

/** Lookup icon by string identifier with safe fallback */
export function getHugeIconByName(name?: string): IconSvgElement {
  if (!name) return CubeIcon;
  return ICON_NAME_MAP[name] || CubeIcon;
}

export interface IconProps extends Omit<HugeiconsProps, 'icon'> {
  name?: string;
  icon?: IconSvgElement;
  size?: number | string;
  className?: string;
  color?: string;
  primaryColor?: string;
  secondaryColor?: string;
  strokeWidth?: number;
  style?: React.CSSProperties;
  title?: string;
  onClick?: (e: React.MouseEvent<SVGSVGElement, MouseEvent>) => void;
}

export const Icon: React.FC<IconProps> = ({
  name,
  icon,
  size = 16,
  color,
  primaryColor,
  secondaryColor,
  strokeWidth,
  className,
  style,
  onClick,
  ...rest
}) => {
  const resolvedIcon = icon || getHugeIconByName(name);
  const finalColor = color || primaryColor || 'currentColor';

  return (
    <HugeiconsIcon
      icon={resolvedIcon}
      size={size}
      primaryColor={finalColor}
      secondaryColor={secondaryColor}
      strokeWidth={strokeWidth}
      className={className}
      style={style}
      onClick={onClick}
      {...rest}
    />
  );
};

export default Icon;
